### ISSUE TITLE
Not Working/Status: Waiting

### ISSUE THREAD

**Issue by ThePescatarian** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#63] opened 2021-10-17 22:47 UTC
I followed the  instructions and enabled game activity on discord. I even disabled and re-enabled. 
![unknown](https://user-images.githubusercontent.com/92696208/137647691-a33ef11b-5ef7-462b-8d3c-bc26916709cd.png)

**Comment by ramkpari** [comment] 2021-10-18 06:18
Hey,
This issue is a duplicate of #59 and is currently being worked on

**Closed** 2021-10-18 09:50 UTC
