### ISSUE TITLE
Mac OS not working.

### ISSUE THREAD

**Issue by parallel-visionz** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#13] opened 2020-04-17 14:40 UTC
Hello! After downloading the MacOS application and running it, it comes with a message that says 

"tidal-rpc cannot be opened because of a problem. - check with the developer to make sure tidal-rpc works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application macOS". 

Is there any idea what's going on that is preventing it from opening?

**Comment by purpl3F0x** [comment] 2020-04-17 16:39
What version of osx are you at?

**Comment by parallel-visionz** [comment] 2020-04-17 16:41
I'm running MacOS Catalina - 10.15.4

**Comment by purpl3F0x** [comment] 2020-04-17 16:46
I'm not sure 'cause I don't have a Mac to test.
But maybe you need to install qt5. Try `brew install qt5` on terminal (I assume you have Homebrew).

**Comment by parallel-visionz** [comment] 2020-04-17 16:58
Okay ill try that.

**Comment by parallel-visionz** [comment] 2020-04-17 17:36
Alright. It worked, thank you!

**Comment by purpl3F0x** [comment] 2020-04-25 21:13
The zip should contain the qt libraries for osx

**Comment by clooney3** [comment] 2020-04-27 21:14
Installing qt5 via homebrew didn't solve this issue for me.

**Comment by purpl3F0x** [comment] 2020-04-28 05:39
Yeah I know what the issue is here. I doesn't pack the dynamic libraries I will fix asap

**Comment by purpl3F0x** [comment] 2020-04-29 08:10
Does it work if you download this [discord_game_sdk.dylib](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/master/discord-game-sdk/lib/x86_64/discord_game_sdk.dylib) and put it on the same directory as the executable ?

**Comment by clooney3** [comment] 2020-04-29 08:23
> Does it work if you download this [discord_game_sdk.dylib](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/master/discord-game-sdk/lib/x86_64/discord_game_sdk.dylib) and put it on the same directory as the executable ?

No, same result.

**Comment by purpl3F0x** [comment] 2020-04-29 08:46
hmm, I'm not sure what is it. Can't really test myself my osx VM is broken atm.
If a previous version works well enough, there isn't very much difference

**Comment by purpl3F0x** [comment] 2021-09-23 14:07
probably fixed on 1.3. Feel Free to open topic again

**Closed by purpl3F0x** 2021-09-23 14:07 UTC
Labels: bug, help wanted
