### ISSUE TITLE
tidal-rpc.exe crashes immediately on Windows 10

### ISSUE THREAD

**Issue by fahei** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#40] opened 2020-10-26 19:22 UTC
- Windows 10: 64Bit 20226.1000
- Discord: Ptb 70385 (23e21e4)
- Tidal: 2.23.0.488
- tidal-rpc: 1.2

When I try to open the tidal-rpc.exe it crashes immediately and Discord opens the home page.

**Comment by purpl3F0x** [comment] 2020-10-26 21:45
Hello,
What does it says as error message ?

**Comment by fahei** [comment] 2020-11-03 00:51
There is no error message. The tidal-rpc closes and opens Discord home page.

**Comment by purpl3F0x** [comment] 2020-11-03 06:17
What's does the error message say?

**Comment by fahei** [comment] 2020-11-03 19:20
Where should the error message be displayed? I can not find anything.

**Comment by fahei** [comment] 2020-11-03 19:22
Don't know why, but the error does not occure anymore. Maybe because of an update of Discord or Tidal.

**Comment by purpl3F0x** [comment] 2020-11-03 19:23
It was probably discord rpc

**Comment by fahei** [comment] 2020-11-09 20:16
Now it does it again ... Actually it worked only once after I closed the issue.

Discord: Ptb 71153 (5139533)

**Comment by purpl3F0x** [comment] 2020-11-11 07:16
I think you should try with normal discord. PTB are test builds

**Comment by LeonZewe** [comment] 2020-11-16 00:50
Also not working for me since a few days. I'm on the stable discord build. Same thing as described above, it just instantly closes and moves discord into the foreground.

**Comment by purpl3F0x** [comment] 2020-11-16 06:24
I will hace to check it then

**Comment by purpl3F0x** [comment] 2020-11-19 08:16
Hello I cannot reproduce the issue after playing some tracks.
```
Stable 71820 (952a581)
Host 0.0.308
Windows 10 64-Bit (10.0.19041)
```

**Comment by purpl3F0x** [comment] 2020-11-27 16:05
closing ?

**Closed by purpl3F0x** 2020-11-27 16:05 UTC
