### ISSUE TITLE
[Windows 10] Disable does not work

### ISSUE THREAD

**Issue by twhitson** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#28] opened 2020-05-20 21:43 UTC
### Steps to reproduce
- Right click Discord Tidal RPC icon in tray
- Disable

### Actual behavior
Discord still says "Playing TIDAL"

### Expected behavior
Discord RPC should go away

**Comment by purpl3F0x** [comment] 2020-05-21 08:34
Caused by the same as #29 
So closing to report on one issue

**Closed by purpl3F0x** 2020-05-21 08:34 UTC
